# Generated by Django 4.1.7 on 2023-03-05 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('P_name', models.CharField(max_length=20)),
                ('P_id', models.IntegerField()),
                ('P_age', models.CharField(max_length=20)),
                ('P_summ', models.CharField(max_length=150)),
            ],
        ),
    ]
