# Generated by Django 4.1.7 on 2023-03-05 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('D_name', models.CharField(max_length=20)),
                ('D_reg_id', models.IntegerField()),
                ('D_qual', models.CharField(max_length=20)),
                ('D_specl', models.CharField(max_length=20)),
            ],
        ),
    ]
