# Generated by Django 4.1.6 on 2023-03-06 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0003_booking_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='contact',
            field=models.IntegerField(default=0),
        ),
    ]
